# Node.js Geospatial microservice deployment V1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geospatial-api-v1
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geospatial-api
      version: v1
  template:
    metadata:
      labels:
        app: geospatial-api
        version: v1
    spec:
      containers:
        - name: geospatial-api
          image: {{ IMAGE_REGISTRY_URL}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            initialDelaySeconds: 180
            periodSeconds: 5
            httpGet:
              port: 3000
              path: /
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: geospatial-keys
                  key: DATABASE_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: geospatial-keys
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: geospatial-keys
                  key: PORT
      imagePullSecrets:
        - name: regcred

# Node.js Geospatial microservice deployment V2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geospatial-api-v2
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geospatial-api
      version: v2
  template:
    metadata:
      labels:
        app: geospatial-api
        version: v2
    spec:
      containers:
        - name: geospatial-api
          image: {{ IMAGE_REGISTRY_URL}}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          livenessProbe:
            initialDelaySeconds: 180
            periodSeconds: 5
            httpGet:
              port: 3000
              path: /
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: geospatial-keys
                  key: DATABASE_URL
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: geospatial-keys
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: geospatial-keys
                  key: PORT
      imagePullSecrets:
        - name: regcred
